# Setup
title: Jerome Faria
tagline: Composer & Sound Artist
url: http://jeromefaria.com
baseurl: ""
analytics_id: UA-33619068-1

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Jerome Faria
  url: https://jeromefaria.bandcamp.com
  email: jerome.faria@gmail.com

# Custom vars
version: 2.0.0

# Gems
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap

# Navigation
navigation:
  - name: About
    url: /about
  - name: Works
    url: /works
  - name: Film & Theatre
    url: /film
  - name: Live
    url: /live
  - name: Press
    url: /press

# Social
social:
  - name: bandcamp
    url: https://jeromefaria.bandcamp.com
  - name: soundcloud
    url: https://soundcloud.com/jeromefaria
  - name: instagram
    url: https://instagram.com/jeromefaria
